version: '3'

services:
        server:
                build: ./server
                volumes:
                        - ./server:/code
                command: bash -c "npm install && npm start"
                ports:
                        - "8080:3000"

        client:
                build: ./client
                volumes:
                        - ./client:/code
                command: bash -c "npm start"
                ports:
                        - "8000:8000"
        db:
                image: mariadb
                environment:
                        MYSQL_ROOT_PASSWORD: "5432"
                        MYSQL_USER: "manager"
                        MYSQL_PASSWORD: "5432"
                        MYSQL_DATABASE: "my_db"

        adminer:
                image: adminer
                restart: always
                ports:
                        - "8800:8080"
